### ISSUE TITLE
run the example, but not success

### ISSUE THREAD

**Issue by honglioslo** [ItziModel/itzi#101]
GRASS 7.8.2 (nc_spm_08_grass7):~/test_itzi/nc_spm_08_grass7 > r.mapcalc exp='n=0.05'
 100%
[Raster MASK present]
GRASS 7.8.2 (nc_spm_08_grass7):~/test_itzi/nc_spm_08_grass7 > itzi run itzi-par.txt
Starting simulation of itzi-par.txt...
WARNING: Temporal database connection defined as:
         /home/honli/test_itzi/nc_spm_08_grass7/-p/tgis/sqlite.db
         But database file does not exist.
WARNING: Error during execution: Traceback (most recent call last):
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/itzi.py", line 165, in sim_runner_worker
    sim_runner.initialize(conf_file).run().finalize()
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/itzi.py", line 101, in initialize
    self.sim.initialize()
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/simulation.py", line 147, in initialize
    self.igis.read(self.in_map_names)
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/gis.py", line 351, in read
    elif self.name_is_stds(self.format_id(map_name)):
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/gis.py", line 308, in name_is_stds
    return bool(tgis.SpaceTimeRasterDataset(name).is_in_db())
  File "/usr/lib/grass78/etc/python/grass/temporal/abstract_dataset.py", line 368, in is_in_db
    return self.base.is_in_db(dbif)
  File "/usr/lib/grass78/etc/python/grass/temporal/base.py", line 315, in is_in_db
    dbif.execute(sql, mapset=self.mapset)
  File "/usr/lib/grass78/etc/python/grass/temporal/core.py", line 990, in execute
    self.msgr.fatal(_("Unable to execute sql statement. " +
  File "/usr/lib/grass78/etc/python/grass/pygrass/messages/__init__.py", line 271, in fatal
    sys.exit(1)
SystemExit: 1

**Comment by honglioslo** [comment]
hi har solved :)

**Comment by MariaRamikh** [comment]
> hi har solved :)

Hi! Could you help? i also have this problem

**Comment by MariaRamikh** [comment]
> Hello @honglioslo Could you explain how you solved the problem? I have the identical error message when trying to run the itzi tutorial example on the North Carolina dataset using GRASS 7.8.6. Many thanks Roy

Hi! It helps in the GRASS window Database tab choose Database>Manage Database>Connect>Check connection parameters, set if uninitialazed - click it, check path and file and run
