### ISSUE TITLE
Use pyswmm for the drainage coupling

### ISSUE THREAD

**Issue by lrntct** [ItziModel/itzi#93]
This would greatly simplify the codebase, and improve maintainability.
See https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/124

On top of the current proposed changes to swmm, the following are necessary:
- An API function to force `AllowPonding`
```
int DLLEXPORT swmm_setAllowPonding(int ap)
// Need to add checks for sim open /started
{
    AllowPonding = ap;
    return 0;
}
```
More likely, it could be a whole `swmm_setSimulationAnalysisSetting` function.
- An API function to get the current time step calling `routing_getRoutingStep`

**Comment by lrntct** [comment]
On top of the current proposed changes to swmm, the following are necessary:
- An API function to force `AllowPonding`
```
int DLLEXPORT swmm_setAllowPonding(int ap)
// Need to add checks for sim open /started
{
    AllowPonding = ap;
    return 0;
}
```
- An API function to get the current time step calling `routing_getRoutingStep`

**Comment by lrntct** [comment]
Since 2785fbb, itzi depends on pyswmm. The results seems OK, but it could be improved with the integration of the coupling functions in swmm.

**Comment by honglioslo** [comment]
I get error run the example with swmm, could tell me how to solve the `error?`

honli@geo135-laptop:~/test_itzi/nc_spm_08_grass7$ itzi run swmm.par
Starting simulation of swmm.par...
Loading libraries from /usr/lib/grass78/lib
WARNING: Error during execution: Traceback (most recent call last):
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/itzi.py", line 165, in sim_runner_worker
    sim_runner.initialize(conf_file).run().finalize()
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/itzi.py", line 101, in initialize
    self.sim.initialize()
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/simulation.py", line 144, in initialize
    self.__set_models(self.igis)
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/simulation.py", line 118, in __set_models
    self.drainage = DrainageSimulation(self.rast_domain,
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/drainage.py", line 39, in __init__
    self.swmm5 = swmm.Swmm5()
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/swmm/swmm.py", line 37, in __init__
    self.c_swmm5 = c.CDLL(swmm_so)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/honli/.local/lib/python3.8/site-packages/itzi/swmm/swmm_c.so: cannot open shared object file: No such file or directory

Exception ignored in: <function DrainageSimulation.__del__ at 0x7fcf78e74e50>
Traceback (most recent call last):
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/drainage.py", line 77, in __del__
    self.swmm5.swmm_end()
AttributeError: 'DrainageSimulation' object has no attribute 'swmm5'


^CProcess Process-1:3:
Traceback (most recent call last):
  File "/home/honli/.local/bin/itzi", line 8, in <module>
    sys.exit(main())
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/itzi.py", line 56, in main
    args.func(args)
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/itzi.py", line 240, in itzi_run
    itzi_run_one(need_grass_session, conf_file, profile)
  File "/home/honli/.local/lib/python3.8/site-packages/itzi/itzi.py", line 184, in itzi_run_one
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
    p.join()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 149, in join
  File "/usr/lib/grass78/etc/python/grass/temporal/c_libraries_interface.py", line 960, in c_library_server
    conn.poll(None)
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
KeyboardInterrupt

**Comment by honglioslo** [comment]
I can run pyswmm from python, but get errors when use itzi

**Comment by Caesar05** [comment]
I get the same error. @honglioslo do you already have a solution for this?

**Comment by EdwardRen951113** [comment]
> Since [2785fbb](https://github.com/ItziModel/itzi/commit/2785fbb5e0c041ed4367eb1634d4d1f93bea67c6), itzi depends on pyswmm. The results seems OK, but it could be improved with the integration of the coupling functions in swmm.

How about the running speed? The former one with .so or the new one with pyswmm, which is faster and more efficient?

**Comment by lrntct** [comment]
@EdwardRen951113 possibly slower, but the original code was a real mess. The new one is much more maintainable and testable.
Since the last release uses pyswmm, I'll close this issue.
